language: node_js
sudo: required
dist: trusty
node_js:
- '6.0'

addons:
  firefox: 46.0
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:

- npm install web-component-tester
- npm install -g bower
- bower install

script:
- xvfb-run wct 

 

